version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:15
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file: .env

  gamedi:
    build: ./
    env_file: .env
    volumes:
      - static:/static
      - media:/app/media
    depends_on:
      - db

  gateway:
    build: ./nginx/
    env_file: .env
    ports:
      - 8000:80
    volumes:
      - static:/static
      - media:/app/media/
    depends_on:
      - db
      - gamedi
