# Generated by Django 5.0.1 on 2024-01-23 07:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0002_alter_game_description_alter_genre_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idempotence_key', models.UUIDField(editable=False, unique=True)),
                ('payment_id', models.UUIDField(editable=False, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=7, verbose_name='Окончательная цена')),
                ('income_without_tax', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=7, verbose_name='Доход без учета налогов')),
                ('status', models.CharField(choices=[('pending', 'Платеж создан и ожидает действий от пользователя.'), ('succeeded', 'Платеж успешно завершен.'), ('canceled', 'Платеж отменен.')], default='pending', editable=False, max_length=20, verbose_name='Статус')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата заказа')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('game', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='games', to='games.game', verbose_name='Игра')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='users', to=settings.AUTH_USER_MODEL, verbose_name='Покупатель')),
            ],
            options={
                'verbose_name': 'Покупка',
                'verbose_name_plural': 'Покупки',
            },
        ),
    ]
