# Generated by Django 5.0.1 on 2024-01-23 14:50

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'Пользователь с таким именем уже существует.'}, help_text='Обязательно. Не более 150 символов. Только латинские буквы, цифры и @/./+/-/_.', max_length=150, unique=True, validators=[users.models.ASCIIUsernameValidator()], verbose_name='Имя пользователя'),
        ),
    ]
