# Generated by Django 4.2.5 on 2023-10-07 14:45

from django.db import migrations, models
import django.db.models.deletion
import games.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Наименование')),
                ('discription', models.TextField(max_length=1024, verbose_name='Описание')),
                ('min_players', models.PositiveSmallIntegerField(verbose_name='Минимальное количество играков')),
                ('max_players', models.PositiveSmallIntegerField(verbose_name='Максимальное количество играков')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Цена')),
                ('discount', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Скидка (%)')),
                ('final_price', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=7, null=True, verbose_name='Окончательная цена')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Игра',
                'verbose_name_plural': 'Игры',
            },
        ),
        migrations.CreateModel(
            name='Gener',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Наименование')),
                ('discription', models.TextField(max_length=1024, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
            },
        ),
        migrations.CreateModel(
            name='GameFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Наименование')),
                ('file', models.FileField(unique=True, upload_to=games.utils.get_file_path, verbose_name='Файл')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='games.game', verbose_name='Игра')),
            ],
            options={
                'verbose_name': 'Файл игры',
                'verbose_name_plural': 'Файлы игр',
            },
        ),
        migrations.AddField(
            model_name='game',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='games', to='games.gener', verbose_name='Жанр'),
        ),
    ]
