# Generated by Django 4.2.5 on 2023-11-08 10:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('games', '0002_rename_gener_genre'), ('games', '0003_rename_discription_game_description_and_more'), ('games', '0004_alter_game_discount_alter_game_final_price_and_more'), ('games', '0005_game_time'), ('games', '0006_alter_game_time')]

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Gener',
            new_name='Genre',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='discription',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='genre',
            old_name='discription',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='game',
            name='discount',
            field=models.DecimalField(decimal_places=0, max_digits=5, verbose_name='Скидка (%)'),
        ),
        migrations.AlterField(
            model_name='game',
            name='final_price',
            field=models.DecimalField(blank=True, decimal_places=0, editable=False, max_digits=7, null=True, verbose_name='Окончательная цена'),
        ),
        migrations.AlterField(
            model_name='game',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=7, verbose_name='Цена'),
        ),
        migrations.AddField(
            model_name='game',
            name='time',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(limit_value=24, message='Количество часов должно быть меньше или равно 24')], verbose_name='Количество игровых часов'),
        ),
    ]
