# Generated by Django 4.2.5 on 2023-10-27 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Gener',
            new_name='Genre',
        ),
    ]
