# Generated by Django 4.2.5 on 2023-10-09 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('games', '0002_game_slug'), ('games', '0003_gener_slug_alter_game_slug')]

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gener',
            name='slug',
            field=models.SlugField(default=1, help_text='Укажите адрес страницы. Используйте только латиницу, цифры, дефисы и знаки подчёркивания', max_length=100, unique=True, verbose_name='Адрес (slug)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='slug',
            field=models.SlugField(help_text='Укажите адрес страницы. Используйте только латиницу, цифры, дефисы и знаки подчёркивания', max_length=100, unique=True, verbose_name='Адрес (slug)'),
        ),
    ]
