# Generated by Django 4.2.5 on 2023-10-08 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='slug',
            field=models.SlugField(default=1, help_text='Укажите адрес для страницы игры. Используйте только латиницу, цифры, дефисы и знаки подчёркивания', max_length=100, unique=True, verbose_name='Адрес игры (slug)'),
            preserve_default=False,
        ),
    ]
