# Generated by Django 4.2.5 on 2023-10-30 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_rename_gener_genre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='discription',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='genre',
            old_name='discription',
            new_name='description',
        ),
    ]
