# Generated by Django 4.2.5 on 2023-10-21 11:16

from django.db import migrations, models
import django.db.models.deletion
import games.utils


class Migration(migrations.Migration):

    replaces = [('games', '0004_admingamefile_usergamefile_game_cover_and_more'), ('games', '0005_admingamefile_order_number_usergamefile_order_number')]

    dependencies = [
        ('games', '0002_game_slug_squashed_0003_gener_slug_alter_game_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminGameFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Наименование')),
                ('file', models.FileField(unique=True, upload_to=games.utils.get_file_path, verbose_name='Файл')),
            ],
            options={
                'verbose_name': 'Файл игры для администратора',
                'verbose_name_plural': 'Файлы игр для администратора',
            },
        ),
        migrations.CreateModel(
            name='UserGameFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Наименование')),
                ('file', models.FileField(unique=True, upload_to=games.utils.get_file_path, verbose_name='Файл')),
            ],
            options={
                'verbose_name': 'Файл игры для пользователя',
                'verbose_name_plural': 'Файлы игр для пользователя',
            },
        ),
        migrations.AddField(
            model_name='game',
            name='cover',
            field=models.ImageField(default=1, unique=True, upload_to=games.utils.get_cover_path, verbose_name='Обложка'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='hover_cover',
            field=models.ImageField(default=1, unique=True, upload_to=games.utils.get_hover_path, verbose_name='Наведение на обложку'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='GameFile',
        ),
        migrations.AddField(
            model_name='usergamefile',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_files', to='games.game', verbose_name='Игра'),
        ),
        migrations.AddField(
            model_name='admingamefile',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_files', to='games.game', verbose_name='Игра'),
        ),
        migrations.AddField(
            model_name='admingamefile',
            name='order_number',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Порядковый номер'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usergamefile',
            name='order_number',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Порядковый номер'),
            preserve_default=False,
        ),
    ]
