# Generated by Django 4.2.7 on 2023-11-12 18:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_rename_gener_genre_squashed_0006_alter_game_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='age_restriction',
            field=models.PositiveSmallIntegerField(default=12, validators=[django.core.validators.MaxValueValidator(limit_value=18, message='Возрастные ограничения могут быть от 0+ до 18+.')], verbose_name='Возрастные ограничения'),
            preserve_default=False,
        ),
    ]
