# Generated by Django 4.2.5 on 2023-10-26 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=7, verbose_name='Окончательная цена')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата заказа')),
                ('game', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='games', to='games.game', verbose_name='Игра')),
            ],
            options={
                'verbose_name': 'Покупка',
                'verbose_name_plural': 'Покупки',
            },
        ),
    ]
